export const QUERY_TAGS = {
  EMPLOYEES: "EMPLOYEES",
  DASHBOARD: "DASHBOARD",
  COMPANIES: "COMPANIES",
  VIP_RESTAURANTS: "VIP_RESTAURANTS",
  RESTAURANT_ADMINS: "RESTAURANT_ADMINS",
  COUPONS: "COUPONS",
  NOTIFICATIONS: "NOTIFICATIONS",
  RESTAURANTS: "RESTAURANTS",
};
